export enum AppState {
  INPUT = 'INPUT',
  STRUCTURE_VIEW = 'STRUCTURE_VIEW',
  SCRIPT_GENERATION = 'SCRIPT_GENERATION'
}

export enum AppTab {
  SEARCH_NICHE = 'SEARCH_NICHE',
  ANALYZE_NICHE = 'ANALYZE_NICHE',
  CALENDAR = 'CALENDAR',
  TOPICS = 'TOPICS',
  PROJECTS = 'PROJECTS',
  SCRIPTS = 'SCRIPTS',
  IMAGES = 'IMAGES',
  SETTINGS = 'SETTINGS'
}

export interface PromptVersion {
  timestamp: number;
  structurePrompt: string;
  scriptPrompt: string;
  note?: string;
}

export interface NicheConfig {
  id: string;
  name: string;
  description?: string;
  workflowDescription?: string; // New field for user notes/mechanics
  defaultDuration: number | string;
  defaultStructureVariants: number | string;
  defaultScriptVariants: number | string;
  
  // Custom Prompts generated by Analysis
  customStructurePrompt?: string;
  customScriptPrompt?: string;
  analyzedKeywords?: string[];
  analyzedTitles?: string[]; // List of video titles used for analysis
  
  // History of prompt changes
  promptHistory?: PromptVersion[];
}

export interface VideoConfig {
  title: string;
  niche: string;
  nicheId?: string; // To track the logic style (e.g., 'war', 'slavery') regardless of display name
  durationMinutes: number;
  structureVariants: number;
  scriptVariants: number;
  releaseDate?: string; // YYYY-MM-DD
}

export interface StructureItem {
  title: string;          // English (primary for script generation)
  titleUa: string;        // Ukrainian (for UI)
  description: string;    // English (primary for script generation)
  descriptionUa: string;  // Ukrainian (for UI)
  estimatedDuration: string;
}

export interface Scene {
  segmentText: string; // The exact slice of script
  segmentTextUa?: string; // Translated segment
  imagePrompt: string; // The generated prompt
  imagePromptUa?: string; // Translated prompt
}

export interface ScriptPart {
  id: string;
  sectionTitle: string;
  contentEn: string;
  contentUa: string;
  isGenerating: boolean;
  warScenes?: Scene[]; // For War Stories niche: segmented visual breakdown
}

export interface ImagePrompt {
  en: string;
  ua: string;
}

export interface GeneratedImage {
  id: string;
  url: string; // base64 data url
  prompt: string;
  aspectRatio: string;
  createdAt: number;
}

export interface Project {
  id: number;
  batchId: string; // To group variants from a single generation run
  config: VideoConfig;
  structure: StructureItem[];
  scriptParts: ScriptPart[];
  isStructureLoading: boolean;
  isScriptGenerating: boolean;
  filename?: string;
  imagePrompts?: ImagePrompt[]; // General prompts (old style)
  imageInstructions?: string;
  isCompleted?: boolean;
  
  // Stored User Instructions
  structureInstructions?: string;
  scriptInstructions?: string;
  
  // New Image Generation Fields
  generatedImages?: GeneratedImage[];
  preferredAspectRatio?: string;
  numberOfImages?: number; // Default 1 if undefined
  numberOfPrompts?: number; // Default 4 if undefined
}

export interface YouTubeVideoData {
  id: string;
  url: string;
  title: string;
  thumbnail: string;
  views: string;
  date: string;
  channelName: string;
  transcript?: string;
  selected?: 'yes' | 'no' | null;
}